# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9ad118636e9ef9b732c70ddb6402dff1dcbcf0c2ce51535d38bed5aac04a5871c706256e58a7184fa063b2a04f50f5bbb210e622057bc2a4a30146313c0e044

test:
  secret_key_base: 796b0a1209cf83db23b1da0993dc110637a72357b0a1bec9d70fcbd6e2375fed351c1035448fdf62258ec55ea2634c5c5663c3cc158242dce3f32de2f9092597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
